### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by thePOET8** [seeyourmind/TKGElib#9]
Have anyone met this？

**Comment by Mistsink** [comment]
@thePOET8 I also encountered this error. May I ask how you resolved it?

**Comment by thePOET8** [comment]
> [@thePOET8](https://github.com/thePOET8) I also encountered this error. May I ask how you resolved it?

Sorry, I can't remember how I resolve it. Maybe about the cuda environment setting or device setting.

**Comment by Mistsink** [comment]
> > [@thePOET8](https://github.com/thePOET8) I also encountered this error. May I ask how you resolved it?
> 
> Sorry, I can't remember how I resolve it. Maybe about the cuda environment setting or device setting.

Tks, Could you please tell me what your CUDA environment is like? Information such as the graphics card model and CUDA version.

**Comment by thePOET8** [comment]
My graphics card model is A30 CUDA 11.8. 
I just ran the code and it worked successfully.
（If you're able to run it successfully and see the performance results, could you let me know? There are also a few other issues discussing performance concerns.）
Below is the output of pip list in the environment：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   2.1.0                    pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
boto3                     1.33.13                  pypi_0    pypi
botocore                  1.33.13                  pypi_0    pypi
ca-certificates           2025.2.25            h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                5.5.2                    pypi_0    pypi
certifi                   2025.1.31                pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
google-auth               2.38.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
greenlet                  3.1.1                    pypi_0    pypi
grpcio                    1.62.3                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
llvmlite                  0.31.0                   pypi_0    pypi
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  2.4                      pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 24.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
path                      16.6.0                   pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.1.2             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.20.3                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pydeprecate               0.3.0                    pypi_0    pypi
python                    3.7.16               h7a1cb2a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         1.3.1                    pypi_0    pypi
pytorch-pretrained-bert   0.6.0                    pypi_0    pypi
pytz                      2025.2                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
regex                     2020.5.14                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.8.2                    pypi_0    pypi
setuptools                65.6.3             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.17.0                   pypi_0    pypi
sqlalchemy                2.0.40                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tk                        8.6.14               h39e8969_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     1.9.0+cu111              pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
torchviz                  0.0.3                    pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.6.4                h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by Mistsink** [comment]
好的好兄弟，我把 cuda 降级试试

**Comment by thePOET8** [comment]
> 好的好兄弟，我把 cuda 降级试试

哦我想起来了，好像是config-default.yaml里的
# Main device to use for this job (e.g., 'cpu', 'cuda', 'cuda:0')
  device: 'cuda:3'

  multi_gpu: False
这里，但是怎么改的我给忘了，大概就是改这个的device设置

**Comment by Mistsink** [comment]
我这边还是不行，貌似是 cuda 版本的问题，后续有结果了我再知会一声哈

**Comment by thePOET8** [comment]
> 我这边还是不行，貌似是 cuda 版本的问题，后续有结果了我再知会一声哈

- OKOK,如果可以的话你可以测测看性能，我看issue里好多说不太一样，我也没成功
